function [ VERTEX,EPV,NoP,NoV,...
    FS,Body,Lateral,Bottom ] = MeshPostProcessing(R_D,H_D)
%This Function Post processes the mesh wich is generated by a mesh
%generator function

%   INPUT ::
%            D,R_D  :: Depth of the Sea,Radius of the Domain
%            a      :: Radius of Sphere
%   OUTPUT ::
%            VERTEX :: the coordinates of each Vertex 
%            EPV    :: number of vertices of each panel.
%                      Marking is done CCW.
%            NoP    :: Number of Panels
%            NoV    :: Number of Vertices
%            Top    :: Indices of Panels which are located on Top face
%            Bottom :: Indices of Panels which are located on Bottom face
%            Lateral:: Indices of Panels which are located on Radius of
%                      the Doamin
%            Body   :: Indices of Panels which are located on Body faces

% Transforming coordinates

load('CylVeryFineMesh');

% VERTEX = a * VERTEX;
% VERTEX = round(VERTEX * 1e2)/1e2;

% Displaying Mesh
figure(11);
patch('faces',EPV,'vertices',VERTEX,'facecol',[.8,.9,1],'edgecol','k');
view(3);
% axis vis3d;

NoP = size(EPV,1);
NoV = size(VERTEX,1);

% Discrimination of Panels for different faces 
FS      = zeros(NoP,1);
Bottom  = zeros(NoP,1);
Lateral = zeros(NoP,1);
Body    = zeros(NoP,1);

for ii=1:size(EPV,1)
    
    X1 = VERTEX(EPV(ii,:),1);
    X2 = VERTEX(EPV(ii,:),2);
    X3 = VERTEX(EPV(ii,:),3);
    
    is1 = find( abs(X3)<1e-4 );
    is2 = find( abs(X3+H_D)<1e-4 );
    
    rr = sqrt(X2.^2 + X1.^2);
    is3 = find( abs(rr-R_D)<1e-4 );
    
    if ( size(is1,1)>2 )
        FS(ii) = ii;
    elseif ( size(is2,1)>2 )
        Bottom(ii) = ii; 
    elseif ( size(is3,1)>2 )
        Lateral(ii) = ii;
    else
        Body(ii) = ii;
    end
    
end

FS      = FS     ( FS     ~=0 );
Bottom  = Bottom ( Bottom ~=0 );
Lateral = Lateral( Lateral~=0 );
Body    = Body   ( Body   ~=0 );

end

